#!/bin/sh
set -e
# Automatically added by dh_icons/12.1.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if which update-icon-caches >/dev/null 2>&1 ; then
		update-icon-caches /usr/share/icons/io.gitlab.hamadmarri.gamma-symbolic.svg /usr/share/icons/io.gitlab.hamadmarri.gamma.svg
	fi
fi
# End automatically added section
